#! /bin/bash
import os
import random
M1 = 0
print ("Please select from an option \n")
print ("\n")
print ("1) Ala is gay \n")
print ("2) Crypted is cool \n")
print ("3) Rock Paper Scissors \n")
print ("\n")
Raw_input(">> ") = M1

If M1 == 1:
 Print ("Confirmed")
 Return 0

If M1 == 2:
 Print ("indeed")
 Return 0

If M1 == 3:

 Print ("beginning game program")
 CPU = random.choice(Rock, Paper, Scissors)
 Player = 0
 os.system("clear”)
 print ("Select an option: \n")
 print ("1) Rock \n")
 print ("2) Paper \n")
 print ("3) Scissors \n")
 print ("\n")
 Raw_input(">> ")= Player

 print ("Rock! \n")
 os.system("sleep 1")
 print ("Paper! \n")
 os.system("sleep 1")
 print ("Scissors! \n")
 os.system("sleep 1")
 print ("\n")

  If Player == "Paper" && CPU == "Rock":
   print ("You win CPU picked: “ + CPU + ".")
  If Player == "Paper" && CPU == "Scissors":
   print ("You lose CPU picked: “ + CPU + ".")
  If Player = CPU:
   print ("It is a draw")
  If Player == "Rock" && CPU == "Paper":
   print ("You lose CPU picked: “ + CPU + ".")
  If Player == "Rock" && CPU == "Scissors":
   print ("You win CPU picked: “ + CPU + ".")
  If Player == "Scissors" && CPU == "Rock":
   print ("You lose CPU picked: “ + CPU + ".")
  If Player == "Scissors" && CPU == “Paper":
   print ("You win CPU picked: “ + CPU + ".")

  os.system("sleep 3")
  break
